spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr_department
    username: postgres
    password: 123

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect